version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/yourdb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
  
  sonarqube:
    image: sonarqube:latest
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"

  # jenkins: // Defines a service named "jenkins".
  #   image: jenkins/jenkins:lts // Specifies the Docker image to be used for the service.
  #   ports: // Exposes ports from the container to the host machine.
  #     - "8080:8080" // Maps port 8080 of the container to port 8080 of the host machine.
  #     - "50000:50000" // Maps port 50000 of the container to port 50000 of the host machine.
  #   volumes: // Mounts volumes to the container.
  #     - jenkins-data:/var/jenkins_home // Mounts the "jenkins-data" volume to the "/var/jenkins_home" directory in the container.
  #     - /var/run/docker.sock:/var/run/docker.sock // Mounts the Docker socket to the container.

volumes:
  mongodb-data:
  # jenkins-data: // Defines a named volume named "jenkins-data".
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: