version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/yourdb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
  
  sonarqube:
    image: sonarqube:latest
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "172.23.64.1:8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mongodb-data:
  jenkins-data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: