pipeline {
    agent any
    tools {nodejs "NodeJS"}
    stages {
        stage('Checkout') {
            steps {
                git url : 'https://github.com/Akuan09/test_repo.git', branch: 'main'
            }
        }
        stage('Test') {
            steps {
                script {
                    sh 'npm install'
                    sh 'npm test'
                }
            }
        }
        stage('SonarQube analysis') {
            script {
                scannerHome = tool "SonarScanner"
            }
            steps {
                // scannerHome = tool 'SonarScanner';
                withSonarQubeEnv('SonarScanner') {
                    sh "${scannerHome}/bin/sonar-scanner"
                }
            }
        }
    }
    post {
        always {
            sh 'echo "Nettoyage en cours..."'
        }
        success {
            sh 'echo "Success"'
            // mail to: 'team@yourdomain.com',
            // subject: "Déploiement réussi: My App ${env.BUILD_NUMBER}",
            // body: "Nouvelle version de l'application déployée en production: ${DOCKER_IMAGE}:${env.BUILD_ID}"
        }
        failure {
            sh 'echo "Failure"'
            // mail to: 'team@yourdomain.com',
            // subject: "Echec du déploiement: My App ${env.BUILD_NUMBER}",
            // body: "Le déploiement a échoué. Veuillez vérifier les logs de jenkins pour plus de détails."
        }
    }
}